### ISSUE TITLE
[Form] Class

### ISSUE THREAD

**Issue by thanhsoncun** [thanhsoncun/CSDLPT_TRACNGHIEM#1]

**Comment by thanhsoncun** [comment]
```
CREATE PROC sp_DanhSachKhoa
@TENSERVER NCHAR(50)
AS
BEGIN
IF (@@SERVICENAME = @TENSERVER)
	BEGIN
		SELECT * FROM KHOA
	END
ELSE
	BEGIN
		SELECT * FROM LINK.TRACNGHIEM.DBO.KHOA
	END
END
```

**Comment by thanhsoncun** [comment]
sp_DanhSachLopTheoKhoa
```
Create proc sp_DanhSachLopTheoKhoa (
	@MAKH NCHAR (8)
)
AS
	if exists(select MALOP from dbo.LOP where MAKH =@MAKH)
		 BEGIN
   			select MALOP,TENLOP from dbo.LOP where MAKH =@MAKH
		 END
	else if exists(select MALOP from LINK.TRACNGHIEM.dbo.LOP where MAKH =@MAKH)
		 BEGIN
   	    	select MALOP,TENLOP from LINK.TRACNGHIEM.dbo.LOP where MAKH =@MAKH
		 END
	else
      	 raiserror ( 'Khong co lop thuoc khoa', 16, 0)
```

**Comment by hhoangna** [comment]
@thanhsoncun  sp viết sai rồi
Sửa lại nè
CREATE PROC sp_DanhSachLopTheoKhoa
	@MAKH NCHAR (8)
AS
	IF EXISTS(SELECT MAKH FROM DBO.LOP WHERE LOP.MAKH =@MAKH)
		 BEGIN
   			SELECT MALOP, TENLOP, MAKH FROM DBO.LOP WHERE LOP.MAKH =@MAKH
		 END
	ELSE IF EXISTS(SELECT MAKH FROM LINK.TRACNGHIEM.DBO.LOP AS P WHERE P.MAKH = @MAKH)
		 BEGIN
   	    	SELECT MALOP, TENLOP, MAKH FROM LINK.TRACNGHIEM.DBO.LOP AS P WHERE P.MAKH = @MAKH
		 END

**Comment by hhoangna** [comment]
CREATE PROC [dbo].[sp_DanhSachLopTheoKhoa_Insert]
@MALOP nchar(8),
@TENLOP nvarchar(40),
@MAKH nchar(8)
AS
BEGIN
	IF (EXISTS(SELECT MALOP FROM DBO.LOP WHERE LOP.MALOP = @MALOP) OR EXISTS(SELECT MALOP FROM LINK.TRACNGHIEM.DBO.LOP AS P WHERE P.MALOP = @MALOP))
		RETURN 1
	ELSE IF (EXISTS(SELECT TENLOP FROM DBO.LOP WHERE LOP.TENLOP = @TENLOP) OR EXISTS(SELECT TENLOP FROM LINK.TRACNGHIEM.DBO.LOP AS P WHERE P.TENLOP = @TENLOP))
		RETURN -1
	ELSE 
		INSERT INTO LOP(MALOP, TENLOP, MAKH) VALUES (@MALOP, @TENLOP, @MAKH)
END

**Comment by hhoangna** [comment]
Done!
