### ISSUE TITLE
From Registration

### ISSUE THREAD

**Issue by thanhsoncun** [thanhsoncun/CSDLPT_TRACNGHIEM#8]
- [x] CreateData
- [x] EditData
- [x] SaveData

**Comment by hhoangna** [comment]
Done

**Comment by thanhsoncun** [comment]
Please check agian. I found some problem when created data, let me know if you can't see it.

**Comment by thanhsoncun** [comment]
I fixed it for you. Could you help me write sp follow method:
sp_FindExam
- Input:
+MASV
+KHOA (if you need)
+Date
+ Something like that
- Output:
- List Exam the user can choose in this day
